version: "3"
services:
  php:
    build: './.docker_images/php'
    image: melnickforever/dm-php
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: './.docker_images/apache/'
    image: melnickforever/dm-apache
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
  db:
    build: './.docker_images/db/'
    image: melnickforever/dm-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - 8090:8080
networks:
  frontend:
  backend:
